/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoGUI;

import Juego.Parcela;
import javax.swing.JLabel;

/**
 *
 * @author alex
 */
public class AnimalGUI extends javax.swing.JPanel {

    private Parcela parcela;
    private boolean prepararProductosSinDestace, prepararProductosConDestace, prepararAlimentar, prepararLimpiar;

    public AnimalGUI(String nombreAnimal, Parcela parcela) {
        initComponents();
        this.parcela = parcela;
        this.nombreAnimal.setText(nombreAnimal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreAnimal = new javax.swing.JLabel();
        vidaAnimal = new javax.swing.JLabel();
        edadAnimal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(vidaAnimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(edadAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edadAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (this.isEnabled()) {

        }
        if (prepararProductosSinDestace) {
            parcela.agregarProductosSinDestace(this);
        }
        if (prepararProductosConDestace) {
            parcela.agregarProductosConDestace(this);
        }
        if (prepararAlimentar) {
            parcela.alimentar(this);
        }
        if (prepararLimpiar) {
            parcela.limpiar(this);
        }
    }//GEN-LAST:event_formMouseClicked

    public boolean isPrepararProductosSinDestace() {
        return prepararProductosSinDestace;
    }

    public void setPrepararProductosSinDestace(boolean prepararProductosSinDestace) {
        this.prepararProductosSinDestace = prepararProductosSinDestace;
    }

    public boolean isPrepararProductosConDestace() {
        return prepararProductosConDestace;
    }

    public void setPrepararProductosConDestace(boolean prepararProductosConDestace) {
        this.prepararProductosConDestace = prepararProductosConDestace;
    }

    public boolean isPrepararAlimentar() {
        return prepararAlimentar;
    }

    public void setPrepararAlimentar(boolean prepararAlimentar) {
        this.prepararAlimentar = prepararAlimentar;
    }

    public boolean isPrepararLimpiar() {
        return prepararLimpiar;
    }

    public void setPrepararLimpiar(boolean prepararLimpiar) {
        this.prepararLimpiar = prepararLimpiar;
    }

    public JLabel getEdadAnimal() {
        return edadAnimal;
    }

    public JLabel getNombreAnimal() {
        return nombreAnimal;
    }

    public JLabel getVidaAnimal() {
        return vidaAnimal;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel edadAnimal;
    private javax.swing.JLabel nombreAnimal;
    private javax.swing.JLabel vidaAnimal;
    // End of variables declaration//GEN-END:variables
}
