/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoGUI;

import Juego.Bodega;
import javax.swing.JTextArea;


/**
 *
 * @author alex
 */
public class BodegaGUI extends javax.swing.JFrame {

    public BodegaGUI() {
        initComponents();
                this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelArriba = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloDestace = new javax.swing.JLabel();
        tituloSinDestace = new javax.swing.JLabel();
        PanelAbajo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PanelCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        existencias = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelArriba.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("   ");
        PanelArriba.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        tituloDestace.setText("Productos");
        jPanel1.add(tituloDestace);

        tituloSinDestace.setText("Existencias");
        jPanel1.add(tituloSinDestace);

        PanelArriba.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelArriba, java.awt.BorderLayout.PAGE_START);

        PanelAbajo.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));
        jPanel3.add(jLabel7);
        jPanel3.add(jLabel25);

        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel10.add(jLabel38, java.awt.BorderLayout.LINE_END);

        jButton1.setText("Salir");
        jPanel10.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel10);

        PanelAbajo.add(jPanel3);

        getContentPane().add(PanelAbajo, java.awt.BorderLayout.PAGE_END);

        PanelCentro.setLayout(new java.awt.GridLayout(1, 2));

        productos.setColumns(20);
        productos.setRows(5);
        jScrollPane1.setViewportView(productos);

        PanelCentro.add(jScrollPane1);

        existencias.setColumns(20);
        existencias.setRows(5);
        jScrollPane2.setViewportView(existencias);

        PanelCentro.add(jScrollPane2);

        getContentPane().add(PanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BodegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BodegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BodegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BodegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new AgregarProductoAnimalesGUI().setVisible(true);
            }
        });
    }

    public JTextArea getExistencias() {
        return existencias;
    }

    public JTextArea getProductos() {
        return productos;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAbajo;
    private javax.swing.JPanel PanelArriba;
    private javax.swing.JPanel PanelCentro;
    private javax.swing.JTextArea existencias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea productos;
    private javax.swing.JLabel tituloDestace;
    private javax.swing.JLabel tituloSinDestace;
    // End of variables declaration//GEN-END:variables
}
