/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoGUI;

import Casillas.Agua;
import CasillasGUI.AguaGUI;
import Juego.Juego;
import javax.swing.JPanel;

/**
 *
 * @author alex
 */
public class JuegoGUI extends javax.swing.JFrame {

    Juego juego;

    public JuegoGUI(Juego juego) {
        initComponents();
        this.juego = juego;
        juego.getGranja().LlenarTablero(this.PanelCentral);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelCentral = new javax.swing.JPanel();
        PanelDerecho = new javax.swing.JPanel();
        desbloqueo = new javax.swing.JToggleButton();
        añadirParcela1 = new javax.swing.JToggleButton();
        añadirPlanta = new javax.swing.JToggleButton();
        cosechar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelCentralLayout = new javax.swing.GroupLayout(PanelCentral);
        PanelCentral.setLayout(PanelCentralLayout);
        PanelCentralLayout.setHorizontalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        PanelCentralLayout.setVerticalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        desbloqueo.setText("desbloqueo");
        desbloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desbloqueoActionPerformed(evt);
            }
        });

        añadirParcela1.setText("Añadir Parcela");
        añadirParcela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirParcela1ActionPerformed(evt);
            }
        });

        añadirPlanta.setText("Añadir Planta");
        añadirPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirPlantaActionPerformed(evt);
            }
        });

        cosechar.setText("Cosechar");
        cosechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosecharActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDerechoLayout = new javax.swing.GroupLayout(PanelDerecho);
        PanelDerecho.setLayout(PanelDerechoLayout);
        PanelDerechoLayout.setHorizontalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añadirPlanta)
                    .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoLayout.createSequentialGroup()
                            .addComponent(desbloqueo)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoLayout.createSequentialGroup()
                            .addComponent(añadirParcela1)
                            .addGap(13, 13, 13)))))
            .addGroup(PanelDerechoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cosechar)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelDerechoLayout.setVerticalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(desbloqueo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(añadirParcela1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(añadirPlanta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cosechar)
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(PanelDerecho, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desbloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desbloqueoActionPerformed
        juego.prepararDesbloqueo();

        if (añadirPlanta.isSelected()) {
            juego.prepararAñadirCultivo();
            añadirPlanta.setSelected(false);
        }
        if (añadirParcela1.isSelected()) {
            juego.prepararAñadirParcela();
            añadirParcela1.setSelected(false);
        }
        if (cosechar.isSelected()) {
            juego.prepararCosechar();
            cosechar.setSelected(false);
        }
    }//GEN-LAST:event_desbloqueoActionPerformed

    private void añadirPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirPlantaActionPerformed
        juego.prepararAñadirCultivo();
        if (desbloqueo.isSelected()) {
            juego.prepararDesbloqueo();
            desbloqueo.setSelected(false);
        }
        if (añadirParcela1.isSelected()) {
            juego.prepararAñadirParcela();
            añadirParcela1.setSelected(false);
        }
        if (cosechar.isSelected()) {
            juego.prepararCosechar();
            cosechar.setSelected(false);
        }
    }//GEN-LAST:event_añadirPlantaActionPerformed

    private void añadirParcela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirParcela1ActionPerformed
        juego.prepararAñadirParcela();
        if (desbloqueo.isSelected()) {
            juego.prepararDesbloqueo();
            desbloqueo.setSelected(false);
        }
        if (añadirPlanta.isSelected()) {
            juego.prepararAñadirCultivo();
            añadirPlanta.setSelected(false);
        }
        if (cosechar.isSelected()) {
            juego.prepararCosechar();
            cosechar.setSelected(false);
        }

    }//GEN-LAST:event_añadirParcela1ActionPerformed

    private void cosecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosecharActionPerformed
        juego.prepararCosechar();
        if (desbloqueo.isSelected()) {
            juego.prepararDesbloqueo();
            desbloqueo.setSelected(false);
        }
        if (añadirPlanta.isSelected()) {
            juego.prepararAñadirCultivo();
            añadirPlanta.setSelected(false);
        }
        if (añadirParcela1.isSelected()) {
            juego.prepararAñadirParcela();
            añadirParcela1.setSelected(false);
        }

    }//GEN-LAST:event_cosecharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        juego.mientras();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new JuegoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelDerecho;
    private javax.swing.JToggleButton añadirParcela1;
    private javax.swing.JToggleButton añadirPlanta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton cosechar;
    private javax.swing.JToggleButton desbloqueo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
