/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoGUI;

import Juego.Parcela;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author alex
 */
public class ParcelaGUI extends javax.swing.JFrame {
    
    private Parcela parcela;
    
    public ParcelaGUI(Parcela parcela) {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.parcela = parcela;
        String precioAnimal = "Precio: "+parcela.getTipo().getPrecio();
        this.precio.setText(precioAnimal);
    }
    
    public JPanel getContenedorAnimalesParcela() {
        return contenedorAnimalesParcela;
    }
    
    public JToggleButton getDestasar() {
        return destasar;
    }
    
    public JToggleButton getRecolectarProductos() {
        return recolectarProductos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        recolectarProductos = new javax.swing.JToggleButton();
        destasar = new javax.swing.JToggleButton();
        agregarAnimal = new javax.swing.JToggleButton();
        cAnimales = new javax.swing.JTextField();
        limpiar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contenedorAnimalesParcela = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(2, 5, 3, 3));

        jButton1.setText("Alimentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        recolectarProductos.setText("Recolectar Producto");
        recolectarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recolectarProductosActionPerformed(evt);
            }
        });
        jPanel3.add(recolectarProductos);

        destasar.setText("Destasar");
        destasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destasarActionPerformed(evt);
            }
        });
        jPanel3.add(destasar);

        agregarAnimal.setText("Agregar Animal");
        agregarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAnimalActionPerformed(evt);
            }
        });
        jPanel3.add(agregarAnimal);
        jPanel3.add(cAnimales);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel3.add(limpiar);
        jPanel3.add(jLabel1);
        jPanel3.add(jLabel2);
        jPanel3.add(jLabel3);
        jPanel3.add(precio);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jLabel8.setText("  ");
        getContentPane().add(jLabel8, java.awt.BorderLayout.LINE_END);

        jLabel7.setText("  ");
        getContentPane().add(jLabel7, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout contenedorAnimalesParcelaLayout = new javax.swing.GroupLayout(contenedorAnimalesParcela);
        contenedorAnimalesParcela.setLayout(contenedorAnimalesParcelaLayout);
        contenedorAnimalesParcelaLayout.setHorizontalGroup(
            contenedorAnimalesParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        contenedorAnimalesParcelaLayout.setVerticalGroup(
            contenedorAnimalesParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        getContentPane().add(contenedorAnimalesParcela, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed

    }//GEN-LAST:event_limpiarActionPerformed

    private void agregarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAnimalActionPerformed
        parcela.llenarParcela(Integer.parseInt(cAnimales.getText()));
        cAnimales.setText("");
    }//GEN-LAST:event_agregarAnimalActionPerformed

    private void recolectarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recolectarProductosActionPerformed
        parcela.prepararProductosSinDestace();
    }//GEN-LAST:event_recolectarProductosActionPerformed

    private void destasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destasarActionPerformed
        parcela.prepararProductosConDestace();
    }//GEN-LAST:event_destasarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       parcela.preparararAlimentar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParcelaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParcelaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParcelaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParcelaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //               new AgregarAnimalesGUI().setVisible(true);
            }
        });
    }
    
    public JLabel getPrecio() {
        return precio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton agregarAnimal;
    private javax.swing.JTextField cAnimales;
    private javax.swing.JPanel contenedorAnimalesParcela;
    private javax.swing.JToggleButton destasar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton limpiar;
    private javax.swing.JLabel precio;
    private javax.swing.JToggleButton recolectarProductos;
    // End of variables declaration//GEN-END:variables
}
