/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoGUI;

import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author alex
 */
public class ReporteGUI extends javax.swing.JFrame {

    /**
     * Creates new form ReporteGUI
     */
    public ReporteGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("REPORTE");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombreJug = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        duraciónPartida = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        oroGeneradoGranja = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        alimentoGeneradoGranja = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        alimentosConsumidos = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cantidadCeldasCompradas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteAnimales = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportesPlanta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("  ");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("  ");
        getContentPane().add(jLabel2, java.awt.BorderLayout.LINE_START);

        jLabel3.setText("  ");
        getContentPane().add(jLabel3, java.awt.BorderLayout.LINE_END);

        jLabel4.setText("  ");
        getContentPane().add(jLabel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setLayout(new java.awt.GridLayout(6, 1));

        jLabel5.setText("NOMBRE:");
        jPanel2.add(jLabel5);
        jPanel2.add(nombreJug);

        jLabel7.setText("DURACIÓN DE LA PARTIDA:");
        jPanel2.add(jLabel7);
        jPanel2.add(duraciónPartida);

        jLabel9.setText("ORO GENERADO POR LA GRANJA: ");
        jPanel2.add(jLabel9);
        jPanel2.add(oroGeneradoGranja);

        jLabel10.setText("ALIMENTO GENERADO:");
        jPanel2.add(jLabel10);
        jPanel2.add(alimentoGeneradoGranja);

        jLabel13.setText("ALIMENTOS CONSUMIDOS:");
        jPanel2.add(jLabel13);
        jPanel2.add(alimentosConsumidos);

        jLabel14.setText("CANTIDAD CELDAS COMPRADAS:");
        jPanel2.add(jLabel14);
        jPanel2.add(cantidadCeldasCompradas);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("REPORTE ANIMALES");
        jPanel3.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        reporteAnimales.setColumns(20);
        reporteAnimales.setRows(5);
        jScrollPane1.setViewportView(reporteAnimales);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("REPORTE DE PLANTAS:");
        jPanel4.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        reportesPlanta.setColumns(20);
        reportesPlanta.setRows(5);
        jScrollPane2.setViewportView(reportesPlanta);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ReporteGUI().setVisible(true);
            }
        });
    }

    public JLabel getAlimentoGeneradoGranja() {
        return alimentoGeneradoGranja;
    }

    public JLabel getAlimentosConsumidos() {
        return alimentosConsumidos;
    }

    public JLabel getCantidadCeldasCompradas() {
        return cantidadCeldasCompradas;
    }

    public JLabel getDuraciónPartida() {
        return duraciónPartida;
    }

    public JLabel getNombreJug() {
        return nombreJug;
    }

    public JLabel getOroGeneradoGranja() {
        return oroGeneradoGranja;
    }

    public JTextArea getReporteAnimales() {
        return reporteAnimales;
    }

    public JTextArea getReportesPlanta() {
        return reportesPlanta;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alimentoGeneradoGranja;
    private javax.swing.JLabel alimentosConsumidos;
    private javax.swing.JLabel cantidadCeldasCompradas;
    private javax.swing.JLabel duraciónPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreJug;
    private javax.swing.JLabel oroGeneradoGranja;
    private javax.swing.JTextArea reporteAnimales;
    private javax.swing.JTextArea reportesPlanta;
    // End of variables declaration//GEN-END:variables
}
