/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CasillasGUI;

import Casillas.Pasto;
import Controladores.ControladorCasillas;
import Controladores.ControladorPasto;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author alex
 */
public class PastoGUI extends javax.swing.JPanel {

    boolean prepararDesbloqueo, prepararAñadirParcela, prepararAñadirCultivo;
    ControladorPasto cPasto = new ControladorPasto();
    Pasto pasto;

    public PastoGUI(Pasto pasto) {
        initComponents();
        indice.setText("Pasto ");
        this.pasto = pasto;
//        probar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indice = new javax.swing.JLabel();
        ParcelaCultivo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        indice.setForeground(new java.awt.Color(0, 0, 0));

        ParcelaCultivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParcelaCultivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indice, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ParcelaCultivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(indice, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ParcelaCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (this.isEnabled()) {

        }
        if (prepararDesbloqueo) {
            ControladorCasillas control = new ControladorCasillas();
            control.desbloquearCasillas(this, Color.GREEN, "Pasto", pasto.getJug());
        }
        if (pasto.parcelaExistente()) {
            pasto.desplegarParcela();
        }
        if (prepararAñadirParcela) {
            pasto.crearParcela(ParcelaCultivo);
        }
        if (pasto.plantaExistente()) {
            pasto.desplegarCultivo();
        }
        if (prepararAñadirCultivo) {
            pasto.sembrar(ParcelaCultivo);

        }
    }//GEN-LAST:event_formMouseClicked

    private void ParcelaCultivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParcelaCultivoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ParcelaCultivoMouseClicked

    public boolean isPrepararDesbloqueo() {
        return prepararDesbloqueo;
    }

    public void setPrepararDesbloqueo(boolean prepararDesbloqueo) {
        this.prepararDesbloqueo = prepararDesbloqueo;
    }

    public boolean isPrepararAñadirParcela() {
        return prepararAñadirParcela;
    }

    public void setPrepararAñadirParcela(boolean prepararAñadirParcela) {
        this.prepararAñadirParcela = prepararAñadirParcela;
    }

    public boolean isPrepararAñadirCultivo() {
        return prepararAñadirCultivo;
    }

    public void setPrepararAñadirCultivo(boolean prepararCultivo) {
        this.prepararAñadirCultivo = prepararCultivo;
    }

    public JLabel getParcelaCultivo() {
        return ParcelaCultivo;
    }

//    public void probar() {
//        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource("grama.jpeg")); // load the image to a imageIcon
//        Image image = imageIcon.getImage();
//        Image newimg = image.getScaledInstance(50,50, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
//        imageIcon = new ImageIcon(newimg);
//        this.ParcelaCultivo.setIcon(imageIcon);
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ParcelaCultivo;
    private javax.swing.JLabel indice;
    // End of variables declaration//GEN-END:variables
}
