/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenusGUI;

import Controladores.ControladorProductos;

/**
 *
 * @author alex
 */
public class AgregarProductoGUI extends javax.swing.JFrame {

    private ControladorProductos controlador;

    public AgregarProductoGUI(ControladorProductos controlador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.controlador = controlador;
        controlador.mostrarListaProductosAnimales(areaTextoProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelArriba = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloDestace = new javax.swing.JLabel();
        PanelAbajo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        agregarProducto = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        tipoProducto = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        precioProducto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PanelCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoProductos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelArriba.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("   ");
        PanelArriba.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        tituloDestace.setText("Productos del Juego");
        jPanel1.add(tituloDestace);

        PanelArriba.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelArriba, java.awt.BorderLayout.PAGE_START);

        PanelAbajo.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("   ");
        jPanel2.add(jLabel3, java.awt.BorderLayout.LINE_END);

        jLabel4.setText("   ");
        jPanel2.add(jLabel4, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.GridLayout(4, 4, 0, 5));
        jPanel4.add(jLabel6);
        jPanel4.add(jLabel5);
        jPanel4.add(jLabel9);
        jPanel4.add(jLabel10);

        jLabel11.setText("Nombre: ");
        jPanel4.add(jLabel11);
        jPanel4.add(nombreProducto);
        jPanel4.add(jLabel13);

        agregarProducto.setText("Añadir Producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        jPanel4.add(agregarProducto);

        jLabel7.setText("Tipo:");
        jPanel4.add(jLabel7);

        tipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimento", "Materia Prima" }));
        jPanel4.add(tipoProducto);
        jPanel4.add(jLabel16);
        jPanel4.add(jLabel8);

        jLabel15.setText("Precio:");
        jPanel4.add(jLabel15);
        jPanel4.add(precioProducto);
        jPanel4.add(jLabel18);
        jPanel4.add(jLabel19);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        PanelAbajo.add(jPanel2);

        getContentPane().add(PanelAbajo, java.awt.BorderLayout.PAGE_END);

        PanelCentro.setLayout(new java.awt.GridLayout(1, 2));

        areaTextoProductos.setColumns(20);
        areaTextoProductos.setRows(5);
        jScrollPane1.setViewportView(areaTextoProductos);

        PanelCentro.add(jScrollPane1);

        getContentPane().add(PanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        areaTextoProductos.setText("");
        controlador.crearProducto(nombreProducto.getText(), (String) tipoProducto.getSelectedItem(), Integer.parseInt(precioProducto.getText()));
        controlador.mostrarListaProductosAnimales(areaTextoProductos);
    }//GEN-LAST:event_agregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new AgregarProductoAnimalesGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAbajo;
    private javax.swing.JPanel PanelArriba;
    private javax.swing.JPanel PanelCentro;
    private javax.swing.JToggleButton agregarProducto;
    private javax.swing.JTextArea areaTextoProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JComboBox<String> tipoProducto;
    private javax.swing.JLabel tituloDestace;
    // End of variables declaration//GEN-END:variables
}
